name: wallet_connect
description: Wallet Connect client made in love with dart.
version: 1.0.3
homepage: https://github.com/Orange-Wallet/wallet-connect-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  web_socket_channel: ^2.1.0
  uuid: ^3.0.4
  http: ^0.13.3
  cryptography: ^2.0.2
  collection: ^1.15.0
  json_annotation: ^4.0.1
  convert: ^3.0.1

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^4.1.4
